name: Create Tag and Publish Release

on: 
  push:
    branches: 
      - main
    tags:
      - v*

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: '${{ secrets.GTHB_TOKEN }}'

  publish_release:
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: '${{ secrets.GTHB_TOKEN }}'
        with:
          args: ${{ env.RELEASE_VERSION }}
