name: Create Tag and Publish Release

on: 
  push:
    branches: 
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: '${{ secrets.GTHB_TOKEN }}'

  publish_release:
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: '${{ secrets.GTHB_TOKEN }}'
        with:
          args: ${{ steps.get_version.outputs.VERSION }}
  
  delete_draft_tags:
    needs: publish_release
    runs-on: ubuntu-latest
    steps:
      - name: Delete draft release tags
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GTHB_TOKEN }}
