name: Create Tag and Publish Release

on:
  push

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: '${{ secrets.GTHB_TOKEN }}'

  publish_release:
    if: '${{ always() }}'
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: '${{ secrets.GTHB_TOKEN }}'
        with:
          args: ${{ github.run_id }}
