name: Create Tag and Publish Release

on: 
  push:
    branches: 
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: '${{ secrets.GTHB_TOKEN }}'

  delete_draft_tags:
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - name: Delete draft release tags
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GTHB_TOKEN }}
